version: "2"

volumes:
  node_modules:
services:
  calm:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=ecto://z5XKESER:LS8jTnO4IZeebZuLJ5@db:5432/calm?ssl=false&pool_size=10"
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/lib/calm/www/node_modules
      ## uncomment the below lines if you want to see the contents of the
      ## container's deps/ and _build/ directories in your local project,
      ## under container_mix
      # - ./container_mix_artifacts:/opt/mix_artifacts

  db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_USER=z5XKESER
      - POSTGRES_PASSWORD=LS8jTnO4IZeebZuLJ5
    ports:
      - 6543:5432
